// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: node/zczh/ZhIQAcquire.proto

#include "node/zczh/ZhIQAcquire.pb.h"
#include "node/zczh/ZhIQAcquire.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace zb {
namespace dcts {
namespace node {
namespace zczh {
namespace zhIQAcquire {

static const char* ZhIQAcquireService_method_names[] = {
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/RealtimeStart",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/GetRealtimeResult",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/RealtimeStop",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/RecordStart",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/RecordStop",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/ReplayTaskStart",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/ReplayRecordQuery",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/ReplayStart",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/GetReplayResult",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/ReplayStop",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/ReplayAdjust",
  "/zb.dcts.node.zczh.zhIQAcquire.ZhIQAcquireService/ReplayTaskStop",
};

std::unique_ptr< ZhIQAcquireService::Stub> ZhIQAcquireService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ZhIQAcquireService::Stub> stub(new ZhIQAcquireService::Stub(channel));
  return stub;
}

ZhIQAcquireService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_RealtimeStart_(ZhIQAcquireService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetRealtimeResult_(ZhIQAcquireService_method_names[1], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_RealtimeStop_(ZhIQAcquireService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RecordStart_(ZhIQAcquireService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RecordStop_(ZhIQAcquireService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReplayTaskStart_(ZhIQAcquireService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReplayRecordQuery_(ZhIQAcquireService_method_names[6], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ReplayStart_(ZhIQAcquireService_method_names[7], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetReplayResult_(ZhIQAcquireService_method_names[8], ::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_ReplayStop_(ZhIQAcquireService_method_names[9], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReplayAdjust_(ZhIQAcquireService_method_names[10], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ReplayTaskStop_(ZhIQAcquireService_method_names[11], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ZhIQAcquireService::Stub::RealtimeStart(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest& request, ::zb::dcts::node::TaskAccount* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest, ::zb::dcts::node::TaskAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RealtimeStart_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::RealtimeStart(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest* request, ::zb::dcts::node::TaskAccount* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest, ::zb::dcts::node::TaskAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RealtimeStart_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::RealtimeStart(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest* request, ::zb::dcts::node::TaskAccount* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RealtimeStart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::TaskAccount>* ZhIQAcquireService::Stub::PrepareAsyncRealtimeStartRaw(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::TaskAccount, ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RealtimeStart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::TaskAccount>* ZhIQAcquireService::Stub::AsyncRealtimeStartRaw(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRealtimeStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::zb::dcts::node::zczh::zhIQAcquire::Result>* ZhIQAcquireService::Stub::GetRealtimeResultRaw(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request) {
  return ::grpc::internal::ClientReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::Result>::Create(channel_.get(), rpcmethod_GetRealtimeResult_, context, request);
}

void ZhIQAcquireService::Stub::experimental_async::GetRealtimeResult(::grpc::ClientContext* context, ::zb::dcts::TaskId* request, ::grpc::experimental::ClientReadReactor< ::zb::dcts::node::zczh::zhIQAcquire::Result>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::Result>::Create(stub_->channel_.get(), stub_->rpcmethod_GetRealtimeResult_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::zb::dcts::node::zczh::zhIQAcquire::Result>* ZhIQAcquireService::Stub::AsyncGetRealtimeResultRaw(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::Result>::Create(channel_.get(), cq, rpcmethod_GetRealtimeResult_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::zb::dcts::node::zczh::zhIQAcquire::Result>* ZhIQAcquireService::Stub::PrepareAsyncGetRealtimeResultRaw(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::Result>::Create(channel_.get(), cq, rpcmethod_GetRealtimeResult_, context, request, false, nullptr);
}

::grpc::Status ZhIQAcquireService::Stub::RealtimeStop(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request, ::zb::dcts::node::NodeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::TaskId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RealtimeStop_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::RealtimeStop(::grpc::ClientContext* context, const ::zb::dcts::TaskId* request, ::zb::dcts::node::NodeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::TaskId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RealtimeStop_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::RealtimeStop(::grpc::ClientContext* context, const ::zb::dcts::TaskId* request, ::zb::dcts::node::NodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RealtimeStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::PrepareAsyncRealtimeStopRaw(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::NodeReply, ::zb::dcts::TaskId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RealtimeStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::AsyncRealtimeStopRaw(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRealtimeStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ZhIQAcquireService::Stub::RecordStart(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount& request, ::zb::dcts::node::NodeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::node::TaskAccount, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RecordStart_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::RecordStart(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount* request, ::zb::dcts::node::NodeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::node::TaskAccount, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RecordStart_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::RecordStart(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount* request, ::zb::dcts::node::NodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RecordStart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::PrepareAsyncRecordStartRaw(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::NodeReply, ::zb::dcts::node::TaskAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RecordStart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::AsyncRecordStartRaw(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecordStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ZhIQAcquireService::Stub::RecordStop(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount& request, ::zb::dcts::node::NodeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::node::TaskAccount, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RecordStop_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::RecordStop(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount* request, ::zb::dcts::node::NodeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::node::TaskAccount, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RecordStop_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::RecordStop(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount* request, ::zb::dcts::node::NodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RecordStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::PrepareAsyncRecordStopRaw(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::NodeReply, ::zb::dcts::node::TaskAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RecordStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::AsyncRecordStopRaw(::grpc::ClientContext* context, const ::zb::dcts::node::TaskAccount& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecordStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ZhIQAcquireService::Stub::ReplayTaskStart(::grpc::ClientContext* context, const ::zb::dcts::node::replay::CreateReplayTaskRequest& request, ::zb::dcts::node::TaskAccount* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::node::replay::CreateReplayTaskRequest, ::zb::dcts::node::TaskAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReplayTaskStart_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::ReplayTaskStart(::grpc::ClientContext* context, const ::zb::dcts::node::replay::CreateReplayTaskRequest* request, ::zb::dcts::node::TaskAccount* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::node::replay::CreateReplayTaskRequest, ::zb::dcts::node::TaskAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayTaskStart_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::ReplayTaskStart(::grpc::ClientContext* context, const ::zb::dcts::node::replay::CreateReplayTaskRequest* request, ::zb::dcts::node::TaskAccount* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayTaskStart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::TaskAccount>* ZhIQAcquireService::Stub::PrepareAsyncReplayTaskStartRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::CreateReplayTaskRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::TaskAccount, ::zb::dcts::node::replay::CreateReplayTaskRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReplayTaskStart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::TaskAccount>* ZhIQAcquireService::Stub::AsyncReplayTaskStartRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::CreateReplayTaskRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReplayTaskStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>* ZhIQAcquireService::Stub::ReplayRecordQueryRaw(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>::Create(channel_.get(), rpcmethod_ReplayRecordQuery_, context, request);
}

void ZhIQAcquireService::Stub::experimental_async::ReplayRecordQuery(::grpc::ClientContext* context, ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordRequest* request, ::grpc::experimental::ClientReadReactor< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>::Create(stub_->channel_.get(), stub_->rpcmethod_ReplayRecordQuery_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>* ZhIQAcquireService::Stub::AsyncReplayRecordQueryRaw(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>::Create(channel_.get(), cq, rpcmethod_ReplayRecordQuery_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>* ZhIQAcquireService::Stub::PrepareAsyncReplayRecordQueryRaw(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>::Create(channel_.get(), cq, rpcmethod_ReplayRecordQuery_, context, request, false, nullptr);
}

::grpc::Status ZhIQAcquireService::Stub::ReplayStart(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest& request, ::zb::dcts::node::NodeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReplayStart_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::ReplayStart(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest* request, ::zb::dcts::node::NodeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayStart_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::ReplayStart(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest* request, ::zb::dcts::node::NodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayStart_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::PrepareAsyncReplayStartRaw(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::NodeReply, ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReplayStart_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::AsyncReplayStartRaw(::grpc::ClientContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReplayStartRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::ClientReader< ::zb::dcts::node::zczh::zhIQAcquire::Result>* ZhIQAcquireService::Stub::GetReplayResultRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::ReplayId& request) {
  return ::grpc::internal::ClientReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::Result>::Create(channel_.get(), rpcmethod_GetReplayResult_, context, request);
}

void ZhIQAcquireService::Stub::experimental_async::GetReplayResult(::grpc::ClientContext* context, ::zb::dcts::node::replay::ReplayId* request, ::grpc::experimental::ClientReadReactor< ::zb::dcts::node::zczh::zhIQAcquire::Result>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::Result>::Create(stub_->channel_.get(), stub_->rpcmethod_GetReplayResult_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::zb::dcts::node::zczh::zhIQAcquire::Result>* ZhIQAcquireService::Stub::AsyncGetReplayResultRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::ReplayId& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::Result>::Create(channel_.get(), cq, rpcmethod_GetReplayResult_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::zb::dcts::node::zczh::zhIQAcquire::Result>* ZhIQAcquireService::Stub::PrepareAsyncGetReplayResultRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::ReplayId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::zb::dcts::node::zczh::zhIQAcquire::Result>::Create(channel_.get(), cq, rpcmethod_GetReplayResult_, context, request, false, nullptr);
}

::grpc::Status ZhIQAcquireService::Stub::ReplayStop(::grpc::ClientContext* context, const ::zb::dcts::node::replay::ReplayId& request, ::zb::dcts::node::NodeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::node::replay::ReplayId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReplayStop_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::ReplayStop(::grpc::ClientContext* context, const ::zb::dcts::node::replay::ReplayId* request, ::zb::dcts::node::NodeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::node::replay::ReplayId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayStop_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::ReplayStop(::grpc::ClientContext* context, const ::zb::dcts::node::replay::ReplayId* request, ::zb::dcts::node::NodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::PrepareAsyncReplayStopRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::ReplayId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::NodeReply, ::zb::dcts::node::replay::ReplayId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReplayStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::AsyncReplayStopRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::ReplayId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReplayStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ZhIQAcquireService::Stub::ReplayAdjust(::grpc::ClientContext* context, const ::zb::dcts::node::replay::AdjustRequest& request, ::zb::dcts::node::NodeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::node::replay::AdjustRequest, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReplayAdjust_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::ReplayAdjust(::grpc::ClientContext* context, const ::zb::dcts::node::replay::AdjustRequest* request, ::zb::dcts::node::NodeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::node::replay::AdjustRequest, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayAdjust_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::ReplayAdjust(::grpc::ClientContext* context, const ::zb::dcts::node::replay::AdjustRequest* request, ::zb::dcts::node::NodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayAdjust_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::PrepareAsyncReplayAdjustRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::AdjustRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::NodeReply, ::zb::dcts::node::replay::AdjustRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReplayAdjust_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::AsyncReplayAdjustRaw(::grpc::ClientContext* context, const ::zb::dcts::node::replay::AdjustRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReplayAdjustRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ZhIQAcquireService::Stub::ReplayTaskStop(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request, ::zb::dcts::node::NodeReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::zb::dcts::TaskId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ReplayTaskStop_, context, request, response);
}

void ZhIQAcquireService::Stub::experimental_async::ReplayTaskStop(::grpc::ClientContext* context, const ::zb::dcts::TaskId* request, ::zb::dcts::node::NodeReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::zb::dcts::TaskId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayTaskStop_, context, request, response, std::move(f));
}

void ZhIQAcquireService::Stub::experimental_async::ReplayTaskStop(::grpc::ClientContext* context, const ::zb::dcts::TaskId* request, ::zb::dcts::node::NodeReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ReplayTaskStop_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::PrepareAsyncReplayTaskStopRaw(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::zb::dcts::node::NodeReply, ::zb::dcts::TaskId, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ReplayTaskStop_, context, request);
}

::grpc::ClientAsyncResponseReader< ::zb::dcts::node::NodeReply>* ZhIQAcquireService::Stub::AsyncReplayTaskStopRaw(::grpc::ClientContext* context, const ::zb::dcts::TaskId& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncReplayTaskStopRaw(context, request, cq);
  result->StartCall();
  return result;
}

ZhIQAcquireService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest, ::zb::dcts::node::TaskAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest* req,
             ::zb::dcts::node::TaskAccount* resp) {
               return service->RealtimeStart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[1],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ZhIQAcquireService::Service, ::zb::dcts::TaskId, ::zb::dcts::node::zczh::zhIQAcquire::Result>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::TaskId* req,
             ::grpc::ServerWriter<::zb::dcts::node::zczh::zhIQAcquire::Result>* writer) {
               return service->GetRealtimeResult(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::TaskId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::TaskId* req,
             ::zb::dcts::node::NodeReply* resp) {
               return service->RealtimeStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::node::TaskAccount, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::TaskAccount* req,
             ::zb::dcts::node::NodeReply* resp) {
               return service->RecordStart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::node::TaskAccount, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::TaskAccount* req,
             ::zb::dcts::node::NodeReply* resp) {
               return service->RecordStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::node::replay::CreateReplayTaskRequest, ::zb::dcts::node::TaskAccount, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::replay::CreateReplayTaskRequest* req,
             ::zb::dcts::node::TaskAccount* resp) {
               return service->ReplayTaskStart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[6],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ZhIQAcquireService::Service, ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordRequest, ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordRequest* req,
             ::grpc::ServerWriter<::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>* writer) {
               return service->ReplayRecordQuery(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[7],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest* req,
             ::zb::dcts::node::NodeReply* resp) {
               return service->ReplayStart(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[8],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< ZhIQAcquireService::Service, ::zb::dcts::node::replay::ReplayId, ::zb::dcts::node::zczh::zhIQAcquire::Result>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::replay::ReplayId* req,
             ::grpc::ServerWriter<::zb::dcts::node::zczh::zhIQAcquire::Result>* writer) {
               return service->GetReplayResult(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[9],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::node::replay::ReplayId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::replay::ReplayId* req,
             ::zb::dcts::node::NodeReply* resp) {
               return service->ReplayStop(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[10],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::node::replay::AdjustRequest, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::node::replay::AdjustRequest* req,
             ::zb::dcts::node::NodeReply* resp) {
               return service->ReplayAdjust(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ZhIQAcquireService_method_names[11],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ZhIQAcquireService::Service, ::zb::dcts::TaskId, ::zb::dcts::node::NodeReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ZhIQAcquireService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::zb::dcts::TaskId* req,
             ::zb::dcts::node::NodeReply* resp) {
               return service->ReplayTaskStop(ctx, req, resp);
             }, this)));
}

ZhIQAcquireService::Service::~Service() {
}

::grpc::Status ZhIQAcquireService::Service::RealtimeStart(::grpc::ServerContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::StartIQRequest* request, ::zb::dcts::node::TaskAccount* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::GetRealtimeResult(::grpc::ServerContext* context, const ::zb::dcts::TaskId* request, ::grpc::ServerWriter< ::zb::dcts::node::zczh::zhIQAcquire::Result>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::RealtimeStop(::grpc::ServerContext* context, const ::zb::dcts::TaskId* request, ::zb::dcts::node::NodeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::RecordStart(::grpc::ServerContext* context, const ::zb::dcts::node::TaskAccount* request, ::zb::dcts::node::NodeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::RecordStop(::grpc::ServerContext* context, const ::zb::dcts::node::TaskAccount* request, ::zb::dcts::node::NodeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::ReplayTaskStart(::grpc::ServerContext* context, const ::zb::dcts::node::replay::CreateReplayTaskRequest* request, ::zb::dcts::node::TaskAccount* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::ReplayRecordQuery(::grpc::ServerContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordRequest* request, ::grpc::ServerWriter< ::zb::dcts::node::zczh::zhIQAcquire::QueryRecordReply>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::ReplayStart(::grpc::ServerContext* context, const ::zb::dcts::node::zczh::zhIQAcquire::ReplayStartRequest* request, ::zb::dcts::node::NodeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::GetReplayResult(::grpc::ServerContext* context, const ::zb::dcts::node::replay::ReplayId* request, ::grpc::ServerWriter< ::zb::dcts::node::zczh::zhIQAcquire::Result>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::ReplayStop(::grpc::ServerContext* context, const ::zb::dcts::node::replay::ReplayId* request, ::zb::dcts::node::NodeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::ReplayAdjust(::grpc::ServerContext* context, const ::zb::dcts::node::replay::AdjustRequest* request, ::zb::dcts::node::NodeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ZhIQAcquireService::Service::ReplayTaskStop(::grpc::ServerContext* context, const ::zb::dcts::TaskId* request, ::zb::dcts::node::NodeReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace zb
}  // namespace dcts
}  // namespace node
}  // namespace zczh
}  // namespace zhIQAcquire

